### ISSUE TITLE
App crashes after "What's new" tab is updated.

### ISSUE THREAD

**Issue by Phmurrph** [bravepipeproject/BraveNewPipeLegacy#3]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [X] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.23.3-2.1.1-2, v0.23.3-2.1.2 and v0.23.3-2.1.3.

### Steps to reproduce the bug

1. Open app.
2. Tap the 'Hamburger' icon.
3. Go to the 'What's new' tab.
4. Update feed.

### Expected behavior

Show the newest uploads by the channels you're subscribed to.

### Actual behavior

App crashes immediately after update.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.3-2.1.3
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept, parameter error
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt:98)
	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 4.4.2 Kitkat

**Comment by evermind-zz** [comment]
Upstream v0.23.3 should also fail did you test that version too?
But I think I've a fix cherry-picked already from upstream.
Could you try this version too [BraveNewPipeDebug.zip](https://github.com/bravenewpipe/BraveNewPipeLegacy/files/12712312/BraveNewPipeDebug.zip) it should contain the fix

**Comment by ShareASmile** [comment]
> Could you try this version too BraveNewPipeDebug.zip

Still crashes with crash report similar to above with reproducible steps described in ISSUE STR (whether you are on android 13)
I installed above debug apk on Samsung galaxyA22 5g device to test quickly)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.3-2.1.3
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept, parameter error
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(Unknown Source:7)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt:98)
	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

**Comment by Phmurrph** [comment]
> Upstream v0.23.3 should also fail did you test that version too? But I think I've a fix cherry-picked already from upstream. Could you try this version too [BraveNewPipeDebug.zip](https://github.com/bravenewpipe/BraveNewPipeLegacy/files/12712312/BraveNewPipeDebug.zip) it should contain the fix

I just tested it: as @ShareASmile mentioned, it still crashes.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.3-2.1.3
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept, parameter error
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$onStartCommand$2.accept(FeedLoadService.kt:98)
	at io.reactivex.rxjava3.internal.observers.BiConsumerSingleObserver.onSuccess(BiConsumerSingleObserver.java:56)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSuccess(SingleDoOnSubscribe.java:77)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)

```
</details>
<hr>

**Comment by evermind-zz** [comment]
Sorry.  I am not sure if I uploaded the right version.  I can reproduce it with the uploaded version.  I'll check it tonight

**Comment by Phmurrph** [comment]
No problem, and thank you for your work, sir :-)

**Comment by evermind-zz** [comment]
This bug is already fixed. Now the correct apk hsould be uploaded here Try this apk
[BraveNewPipeDebug.zip](https://github.com/bravenewpipe/BraveNewPipeLegacy/files/12719089/BraveNewPipeDebug.zip)

**Comment by Phmurrph** [comment]
Just tried it: app won't install.

**Comment by ShareASmile** [comment]
> Just tried it: app won't install.

No problems here, have you uninstalled first debug apk given in this [comment](https://github.com/bravenewpipe/BraveNewPipeLegacy/issues/3?notification_referrer_id=NT_kwDOA5sJgbM3ODMxNzM5MTI2OjYwNDkyMTYx#issuecomment-1733080626)

You cannot install second debug apk over the top of first one because of different signing signatures.

& it works, Thanks to evermind-zz.

**Comment by Phmurrph** [comment]
> > Just tried it: app won't install.
> 
> No problems here, have you uninstalled first debug apk given in this [comment](https://github.com/bravenewpipe/BraveNewPipeLegacy/issues/3?notification_referrer_id=NT_kwDOA5sJgbM3ODMxNzM5MTI2OjYwNDkyMTYx#issuecomment-1733080626)
>

Yup.
