### ISSUE TITLE
Videos and BraveNewPipe are loading very slowly.

### ISSUE THREAD

**Issue by ghost** [bravepipeproject/BraveNewPipeLegacy#4]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/polymorphicshade/NewPipe/releases/latest).
- [ ] I am *not* able to reproduce the bug with the *same version* of [upstream NewPipe](https://github.com/TeamNewPipe/NewPipe/releases/).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3-2.1.6 (also some older versions too)

### Steps to reproduce the bug

1. Open BraveNewPipe (loading very slowly all the videos and BraveNewPipe slowly too)
2. Play any video (it'll be slow)

### Expected behavior

The video and BraveNewPipe should load in less than 1-2 seconds.

### Actual behavior

BraveNewPipe in general loads very slowly too
The video loads in 30+ seconds or even more.

### Screenshots/Screen recordings

[bravenewpipe.zip](https://github.com/bravenewpipe/BraveNewPipeLegacy/files/13328661/bravenewpipe.zip)

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED] occurred while playing https://www.youtube.com/watch?v=VPL8fULxMOw
* __Content Country:__ BG
* __Content Language:__ bg-BG
* __App Language:__ bg_BG
* __Service:__ YouTube
* __Version:__ 0.23.3-2.1.6
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host "rr2---sn-uxaxiv0nxx5q-nv4l.googlevideo.com": No address associated with hostname
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.UnknownHostException: Unable to resolve host "rr2---sn-uxaxiv0nxx5q-nv4l.googlevideo.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
	at java.net.InetAddress.getAllByName(InetAddress.java:214)
	at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:390)
	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:343)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more
Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
	... 24 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 4.4.2 / Stock TouchWiz rom

### Affected device model

Samsung Galaxy S3 Neo (GT-I9301I)

### Additional information

Before BraveNewPipe also used to load videos slowly, but now its so slow that it is unbearable..
A video with these bugs has been uploaded.

**Comment by ghost** [comment]
It's been 1 month.

**Comment by ghost** [comment]
3 months

**Comment by evermind-zz** [comment]
I am sorry for this but I have no time to maintain this app at the moment
